import {useCallback,useRef,useState} from 'react';
declare global{interface Window{SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike}}
interface SpeechRecognitionLike{lang:string;interimResults:boolean;continuous:boolean;start():void;stop():void;abort():void;addEventListener(type:string,cb:(e:any)=>void):void}
export function useSpeechRecognition(onFinal:(text:string)=>void){
 const[listening,setListening]=useState(false);const[transcript,setTranscript]=useState('');const[error,setError]=useState('');const current=useRef<SpeechRecognitionLike|null>(null);const timer=useRef<number|undefined>(undefined);const supported=typeof window!=='undefined'&&!!(window.SpeechRecognition||window.webkitSpeechRecognition);
 const stop=useCallback(()=>{setListening(false);const r=current.current;if(!r)return;try{r.stop()}catch{current.current=null}window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>{try{r.abort()}catch{current.current=null}},500)},[]);
 const start=useCallback(()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setError('Voice recognition is unavailable. Type a command instead.');return}window.speechSynthesis?.cancel();setError('');setTranscript('');const r=new SR();current.current=r;r.lang='en-US';r.interimResults=true;r.continuous=false;r.addEventListener('start',()=>setListening(true));r.addEventListener('result',(e:any)=>{let final='',interim='';for(let i=0;i<e.results.length;i++){const chunk=e.results[i][0].transcript;if(e.results[i].isFinal)final+=chunk;else interim+=chunk}setTranscript((final||interim).trim())});r.addEventListener('end',()=>{window.clearTimeout(timer.current);setListening(false);if(current.current===r)current.current=null;setTranscript(value=>{if(value)onFinal(value);return value})});r.addEventListener('error',(e:any)=>{setListening(false);if(current.current===r)current.current=null;if(!['aborted','no-speech'].includes(e.error))setError(e.error==='not-allowed'?'Microphone permission denied. Use the typed command below.':`Voice error: ${e.error||'unknown'}`)});try{r.start();setListening(true)}catch{current.current=null}},[onFinal]);
 return{supported,listening,transcript,error,start,stop};
}
